### ISSUE TITLE
Inconsistent with AutoPhrase

### ISSUE THREAD

**Issue by Kyon-N** [mickeystroller/SetExpan#2]
In /src/corpusProcessing/corpusProcess.sh line 24, pass 3 command line parameters to phrasal_segmentation.sh, but this script in project AutoPhrase doesn't accept parameters.

**Comment by mickeysjm** [comment]
Hi, @Kyon-N sorry for the late reply due to some paper deadlines. I have uploaded the modified version of phrasal_segmentation.sh. You just need to replace the one in the original AutoPhrase repo with the current new one.
