### ISSUE TITLE
Clarification about Wikipedia test set and number of entities in wikipedia data.

### ISSUE THREAD

**Issue by se4u** [mickeystroller/SetExpan#3]
Hi, 

Thank you for open sourcing the code for `SetExpan: Corpus-Based Set Expansion via
Context Feature Selection and Rank Ensemble`. 

In Table 1 you mention that you created 20 queries for evaluating your system and then used students to label the answers of the queries.  Can you release the queries and their labeled answers please. My second question is that in Table 1 you mention that there are `710K` entities in the wikipedia dataset but the wiki dataset that I downloaded from the google drive link only contains `33K` entities even though it does have `1.5M` sentences as stated in Table 1.

```
$ grep -o '"entityId": [0-9]*'  data/wiki/source/sentences.json | awk '{print $2}' | sort -u | wc -l 
33288
$ wc -l  data/wiki/source/sentences.json
1,505,765
```

Can you please release the query data and clarify regarding the number of entities please.
Thanks,
Pushpendre

**Comment by mickeysjm** [comment]
Hi @se4u,

Thanks for contacting us, I upload all the Wikipedia queries in the repo. 

Also, the "entity2id.txt" we used in the original paper is the full version of entity2id which contains about 710K entities and the one you download from google drive link contains only 33k entities that have the frequency above a threshold (10, if I remember correctly). Thanks for pointing the error in entity2id.txt. I have also uploaded the original one in this repo. 

Thanks,
--Jiaming

**Comment by se4u** [comment]
Hi Jiaming, thanks for the quick reply. I think you forgot to add the `data/wiki-supplementary/*` files in the repo. Your latest commit only changed the `.gitignore` file

**Comment by mickeysjm** [comment]
Thanks, I fix this issue and re-upload the files

**Comment by se4u** [comment]
Thanks a lot for uploading your dataset. One last question, can you also say which SEISA implementation did you use please ? I could not find any standard SEISA implementation online.

**Comment by mickeysjm** [comment]
Yes, there is no open-sourced SEISA implementation online and we implement this algorithm ourselves. I will first ask my collaborator and see whether we can find its original implement. If we are able to find it, we will also release that implementation and inform you by email. 

Thanks
