### ISSUE TITLE
No public access to provided preprocessed data on Google Drive

### ISSUE THREAD

**Issue by sythello** [mickeystroller/SetExpan#5]
Hello! Thank you for sharing the code!

I was trying out the code and wanted to download the preprocessed data from the provided link to Google drive, but it asks for access. Would you like to provide public access to the data, or should we send access requests individually if we want to download it? Thanks again!

**Comment by mickeysjm** [comment]
I have updated this dataset link and you can check it now. Thanks.

**Comment by sythello** [comment]
Thank you!
